[package]
name = "mockserver"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
serde_yaml = "0.9.34"
tokio = { version = "1.44.1", features = ["full"] }
warp = "0.3.7"
anyhow = "1.0.97"
bytes = "1.10.1"
base64 = "0.21.7"
serde_json = "1.0.140"