/api/user:
  method:
   - GET
  file: user_response.json

/api/order:
  method:
   - POST
   - DELETE
  file: order_data.json
  status_code: 202 #custom Http Status code
  authentication:
    bearer:
      token: TOKEN_STR
      claims:
        sub: SUB
        name: NAME
        iat: 1516238972