/api/user:
  method:
   - GET
  file: user_response.json
  delay: 3000 # in ms

/api/user/1:
  method:
    - GET
  file: user_response.json
  rate_limit:
    requests: 5
    window_ms: 10000

/api/order:
  method:
   - POST
   - DELETE
  file: order_data.json
  status_code: 202 #custom Http Status code
  authentication:
    bearer:
      token: TOKEN_STR
      claims:
        sub: SUB
        name: NAME
        iat: 1516238972