name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  push:
    tags:
      - "v*"  # Runs when pushing a tag like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build (Debug)
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build (Release)
      run: cargo build --release --verbose

    - name: Upload Release Binary
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir -p dist
        cp target/release/myapp dist/
        tar -czvf dist/myapp-${{ github.ref_name }}-linux.tar.gz -C dist myapp

    - name: Publish to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/myapp-${{ github.ref_name }}-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
